<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-N6BIESD" failures="1" tests="4" name="com.numeracle.tests.NumberCheckTest" time="19.347" errors="0" timestamp="2023-06-22T18:13:25 IST" skipped="0">
  <testcase classname="com.numeracle.tests.NumberCheckTest" name="testLogin" time="6.178"/>
  <system-out/>
  <testcase classname="com.numeracle.tests.NumberCheckTest" name="testLogin" time="6.635"/>
  <system-out/>
  <testcase classname="com.numeracle.tests.NumberCheckTest" name="testhome" time="3.121"/>
  <system-out/>
  <testcase classname="com.numeracle.tests.NumberCheckTest" name="testhome" time="3.413">
    <failure message="String Match expected [SUCCESS!
User Login Successful] but found [ERROR!
[object Object]]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: String Match expected [SUCCESS!
User Login Successful] but found [ERROR!
[object Object]]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at com.cynnent.utils.TestNGUtils.assertEquals(TestNGUtils.java:39)
at com.numeracle.tests.NumberCheckTest.testhome(NumberCheckTest.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- testhome -->
  <system-out/>
</testsuite> <!-- com.numeracle.tests.NumberCheckTest -->
